In [1]:
# Project Outline & Problem Definition 

# The purpose of this codelab/notebook is to reproduce and test the findings & conclusions   
# from the 2015 paper, '[Facebook] Comment Volume Prediction Using Decision Trees & Neural Networks.' 
# The goal of the exercise is to build & compare models that predict how many comments a particular FB post or 
# page will receive over a set period of time, using the provided data sets acquired from the [UC Irvine Machine 
# Learning Repository](https://archive.ics.uci.edu/ml/datasets/Facebook+Comment+Volume+Dataset)

# The predictive modelling techniques used in this notebook are Decision Trees (specifically, REP & M5P Trees) and 
# Neural Networks (specifically, a Multi-Layer Preceptron, and an RBF Network).

# The metrics used to evaluate model performance were Hits@10, AUC@10, MAE & Evaluation Time.

In [21]:
# Import Libraries & Training Data  
import pandas as pd
import glob

path =r'/Users/MillersFiles/Documents/Data Science/U of T Data Science Program/3253/Final Project/Dataset/Training' # use your path
allFiles = glob.glob(path + "/*.csv")
frame = pd.DataFrame()
list_ = []
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0,)
    list_.append(df)
training_data = pd.concat(list_)

In [22]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 602808 entries, 0 to 199028
Columns: 116 entries, -0.8625954198473282 to 96.7997690772648
dtypes: float64(88), int64(28)
memory usage: 538.1 MB

In [61]:
train_data = pd.read_csv("/Users/MillersFiles/Downloads/Dataset/Training/Features_Variant_1.csv",header=true)
train_data.head(10)

,634995,0,463,1,0.0,806.0,11.291044776119403,1.0,70.49513846124168,0.0.1,...,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,1.2,0.19
0,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,0,0,0,0,0,0,0,1,0,0
1,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,1,0,0,0,0,0,0,0,1,0
2,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,1,0,0,1,0,0,0,0,0,0
3,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,0,0,0,0,0,1,0,0,0,0
4,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,0,0,0,0,0,0,0,1,0,0
5,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,0,0,0,0,0,0,0,0,1,0
6,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,0,0,0,0,0,0,0,0,1,0
7,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,1,0,0,0,0,0,0,0,1,0
8,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,1,0,1,0,0,0,0,0,0,0
9,634995,0,463,1,0.0,806.0,11.291045,1.0,70.495138,0.0,...,1,0,1,0,0,0,0,0,0,0